{ api_timeout = None Natural
, auth = None ../JSON.dhall
, auth_type = None Text
, availability_zone = None Text
, ca_cert = None Text
, client_cert = None Text
, client_key = None Text
, cloud = None Text
, description = None Text
, interface = None ./interface.dhall
, records = None (List Text)
, recordset_type = None ./recordset_type.dhall
, region_name = None Text
, state = None ./state.dhall
, timeout = None Natural
, ttl = None Natural
, validate_certs = None Bool
, wait = None Bool
}